Popup window
mwanawabangona/mobile-portfolio pull request #12
Opened 2021-08-06 11:11 UTC by mwanawabangona

My-Portfolio, Popup window

 -Add Html file
 -Add js file
 -Add CSS file
 -Add Github folder in which includes linters.yml file
 -Add gitignore file in which includes node-module/ and Vscode files
 -Add Linters config files

2021-08-06 12:22 UTC, Davidosky007 requested changes
# Hi @mwanawabangona 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
* Kindly write your commit message in the imperative mood (ie Fix and not Fixed or Fixes) this is the best practice [Read more here on how to properly write commit messages ](https://medium.com/@steveamaza/how-to-write-a-proper-git-commit-message-e028865e5791)
* I suggest you use the project object created to populate the project section on page load and not hard code it with `HTML` check comments below and make necessary changes 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
-N.A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-06 12:22 UTC, Davidosky007 commented on index.html
> +                            </div>
* The technologies tag are overflowing hence causing the popup window to stretch for both desktop and mobile views kindly fix it 🙏 
![image](https://user-images.githubusercontent.com/52497246/128507141-b9993e36-a7fb-477a-adf7-1cbb262b0c94.png)
![image](https://user-images.githubusercontent.com/52497246/128507189-9f42580f-9d44-46db-904c-49e3ecb83812.png)

2021-08-06 12:22 UTC, Davidosky007 commented on js/popup.js
> +    tags: ['html', 'css', 'javaScript'],
* Kindly add the link to the live version and link to source in each object as it is stated in the project requirement it should be included here in each object [Refer to the project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md#:~:text=For%20each%20project%20you%20need%20to%20store%20the%20following%20pieces%20of%20data%20in%20a%20JavaScript%20object%2C%20at%20a%20minimum%3A%20name%2C%20description%2C%20featured%20image%2C%20technologies%2C%20link%20to%20live%20version%2C%20link%20to%20source.)

2021-08-06 12:22 UTC, Davidosky007 commented on index.html
> +                            </p>
* Kindly load each project content from the array of objects created and not hard code it using `HTML` doing so would make addition and subtraction of projects in the future easy plus it is a requirement for this project [Check Here](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md#:~:text=For%20each%20project,the%20page%20loads.)

2021-08-07 01:15 UTC, bellom commented on index.html
> +                            </div>
@mwanawabangona,

Mobile Version:
Let's give some margin between span and the buttons.
Let's fix the border for the button too, kindly make it look like the original design,

Original Design:
![image](https://user-images.githubusercontent.com/31897434/128583323-62220c97-be58-451f-8f8b-6b153300b615.png)

Your app:
![image](https://user-images.githubusercontent.com/31897434/128583343-d8e7b061-7292-4bb6-a781-a5847fd0e875.png)

2021-08-07 01:16 UTC, bellom requested changes
## Hi @mwanawabangona  👏 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some little styling to fix.

 ## Required Changes ♻️
 
_Check the comments above the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-07 05:22 UTC, hemant-soni-vst-au4 approved these changes
Hi @mwanawabangona, 

Good work on making the requested changes. 🚀 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/jkZhf5HyZkLbBzzZsn/giphy.gif)

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-07 06:31 UTC, merged