Collabo branch
mwanawabangona/mobile-portfolio pull request #2
Opened 2021-07-20 20:57 UTC by mwanawabangona

This project is inspired by Figma templates, I have remade a Figma template and invited my programming partners to come to see if there is any change needed on the project.

2021-07-20 23:07 UTC, Emmyn5600 requested changes
## STATUS: Changes Requested :recycle:

Hi @mwanawabangona 

Good job so far!:clap::clap:
You have done well in implementing the project requirements :clap:, However, there are some issues that you still need to work on to go to the next project but you are almost there!:muscle:

##  Required Changes:writing_hand:
  
**_Check the comments under the review._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-07-20 23:07 UTC, Emmyn5600 commented on index.html
> +</section>
- [ ] Please make sure you are calling your CSS properly, Look at the image below for more details, it is displaying nothing.
![form3](https://user-images.githubusercontent.com/55635977/126405820-96472d38-f736-4896-b648-ae4120f5600d.png)
- [ ] Form uses the action and method attribute to integrate with [formspree](https://formspree.io/html) service.

         * action value should be similar to https://formspree.io/f/{form_id}
         * method value equals POST

2021-07-20 23:07 UTC, Emmyn5600 commented on index.html
> +</p>
- [ ] Use h1 or h2 tag for Contact me instead of p tag

2021-07-20 23:07 UTC, Emmyn5600 commented on README.md
> +
- [ ] Kindly, add the live link demo which working properly.
![livelink](https://user-images.githubusercontent.com/55635977/126406149-c7c156bd-bd7d-486d-8a88-c9f49130c91c.png)

2021-07-20 23:07 UTC, Emmyn5600 commented on index.html
> +  </section>
- [ ] Please add hover color to the `see project` button and add some padding between the project technology.

2021-07-21 12:51 UTC, hemant-soni-vst-au4 requested changes
Hi @mwanawabangona , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there! 

![Alt Text](https://media.giphy.com/media/q6U4fbreC4Neo/giphy.gif)
## Required Changes ♻️
_Check the comments under the review._

Cheers,
Hemant Soni
Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-21 12:51 UTC, hemant-soni-vst-au4 commented on css/style.css
> +}
- [ ] There is too much of width which leads to horizontal scrolling of the page. Kindly try to fix the positioning issue of the form section.

![image](https://user-images.githubusercontent.com/53019916/126491269-7d242f7a-1b0b-4693-83d0-6b83fdda9c92.png)

2021-07-21 16:03 UTC, Emmyn5600 approved these changes
## STATUS: APPROVED :muscle::clap:

Hi, @mwanawabangona 

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:


Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-07-21 16:48 UTC, Emmyn5600 commented
Hi @mwanawabangona and the next code reviewer, I approved the changes by mistake on the GitHub review changes. Please ignore the above message saying  `Emmyn5600 approved these changes`

2021-07-21 17:09 UTC, mwanawabangona commented
ok

On Wed, Jul 21, 2021 at 6:49 PM Emmy NSABIMANA ***@***.***>
wrote:

> Hi @mwanawabangona <https://github.com/mwanawabangona> and the next code
> reviewer, I approved the changes by mistake on the GitHub review changes.
> Please ignore the above message saying Emmyn5600 approved these changes
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mwanawabangona/mobile-portfolio/pull/2#issuecomment-884337082>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APZJQIR3TJHHM3NJ4MS7SX3TY3277ANCNFSM5AWSW4GA>
> .
>

2021-07-23 00:17 UTC, Shaher-11 approved these changes
#### Hello @mwanawabangona,

# Congratulations! 🎉 
#### Your project is approved!  There is nothing else to say other than... it's time to merge it :muscle: :muscle::muscle:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

2021-07-26 15:40 UTC, merged