Desktop portfolio
mwanawabangona/mobile-portfolio pull request #5
Opened 2021-07-23 14:41 UTC by mwanawabangona

This project is inspired by Figma templates, I used HTML and CSS to build a Desktop/mobile responsive website template.

2021-07-23 16:17 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [ ] Check the comments under the review.
- [ ] Please, work in your PR description following the [Professional repository rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=Write%20a%20meaningful%20title%20for%20your%20pull%20request%20and%20always%20add%20a%20short%20summary%20of%20changes%20introduced%20in%20the%20pull%20request.)
![image](https://user-images.githubusercontent.com/20563252/126811362-b5bc8def-4c44-4c24-8508-584c3b6c017c.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-23 16:17 UTC, vichuge commented on index.html
> +                      </li>
- [ ] It looks like some project has a different size on the list, I kindly invite you to work on it.
- [ ] The background color could improve too. 🐶 

| Original | your project |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/20563252/126810083-782d7bf9-0768-409e-8e80-558714b65f30.png) | ![image](https://user-images.githubusercontent.com/20563252/126810178-dac0f1a7-ce41-4635-86ac-5662646a354a.png) |

2021-07-23 16:17 UTC, vichuge commented on index.html
> +    </form>
- [ ] On desktop size, the form inputs stop to use all the weight screens, look at the original template and please, fix it. 🐱

| original | your project |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/20563252/126810422-a6dbd278-633d-4eff-8119-7d25d2577c99.png) | ![image](https://user-images.githubusercontent.com/20563252/126810463-0808760a-3939-40ec-8f26-092188708e19.png) |

2021-07-23 16:17 UTC, vichuge commented on css/style.css
> +@media only screen and (min-width: 768px) {
- [ ] Uses media queries for the Desktop breakpoint in the CSS file. (the value for min-width property should be in range of 992px - 1100px). Please fix this. 🌵

2021-07-23 16:17 UTC, vichuge commented on css/style.css
> +@media only screen and (max-width: 769px) {
- [ ] I kindly remind you, consider the mobile phone when you work on the desktop size, this should work as usual when you finish your desktop size, following your own deployment, this is how the mobile size looks using chrome web tools. I kindly invite you to work on this. 🐦 
![image](https://user-images.githubusercontent.com/20563252/126811072-c06935ee-f5d1-46bd-8fb2-31d02f65959d.png)

2021-07-24 00:39 UTC, carlos-ssh approved these changes
Hi @mwanawabangona , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-26 15:40 UTC, merged